#!/usr/bin/env python3
"""
Helper function to map team names to Wikipedia page titles.
"""
import json
import os
from pathlib import Path

# Load the Big Ten mapping
def load_big_ten_mapping():
    """Load the Big Ten team name to Wikipedia page title mapping."""
    script_dir = Path(__file__).parent
    mapping_file = script_dir.parent / 'test_data' / 'big_ten_wikipedia_pages.json'
    
    if mapping_file.exists():
        with open(mapping_file, 'r', encoding='utf-8') as f:
            data = json.load(f)
            mapping = {}
            for result in data.get('results', []):
                if result.get('found') and result.get('has_infobox'):
                    team_name = result['team_name']
                    page_title = result['page_title']
                    mapping[team_name.lower()] = page_title
            return mapping
    return {}


def get_wikipedia_page_title(team_name):
    """
    Get Wikipedia page title for a team name.
    
    Args:
        team_name: Team name (e.g., "UCLA", "Michigan State", "Oregon")
    
    Returns:
        Wikipedia page title, or None if not found
    """
    # Load Big Ten mapping
    big_ten_mapping = load_big_ten_mapping()
    
    # Try exact match (case-insensitive)
    team_key = team_name.lower()
    if team_key in big_ten_mapping:
        return big_ten_mapping[team_key]
    
    # Try common variations
    variations = [
        team_name,
        team_name + " men's basketball",
        team_name.replace("State", "State Spartans") + " men's basketball",
        team_name.replace("State", "State Boilermakers") + " men's basketball",
        # Add more variations as needed
    ]
    
    # For now, return a constructed title based on common pattern
    # Most teams follow: "{Team Name} {Mascot} men's basketball"
    # This is a fallback - ideally we'd have a comprehensive mapping
    return None


# Common team name to Wikipedia page title mappings
# Based on teams from bballnet.com and common searches
TEAM_WIKIPEDIA_MAPPING = {
    ' cajuns': "Louisiana Ragin\' Cajuns men\'s basketball",
    '1895–96': "collegiate men's basketball season in the United States",
    '1896–97': "collegiate men's basketball season in the United States",
    '1897–98': "collegiate men's basketball season in the United States",
    '1898–99': "collegiate men's basketball season in the United States",
    '1899–1900': "collegiate men's basketball season in the United States",
    '1900–01': "collegiate men's basketball season in the United States",
    '1901–02': "collegiate men's basketball season in the United States",
    '1902–03': "collegiate men's basketball season in the United States",
    '1903–04': "collegiate men's basketball season in the United States",
    '1904–05': "collegiate men's basketball season in the United States",
    '1905–06': "collegiate men's basketball season in the United States",
    '1906–07': "IAAUS men's basketball season",
    '1907–08': "IAAUS men's basketball season",
    '1908–09': "IAAUS men's basketball season",
    '1909–10': "IAAUS men's basketball season",
    '1910–11': "NCAA men's basketball season",
    '1911–12': "NCAA men's basketball season",
    '1912–13': "NCAA men's basketball season",
    '1913–14': "NCAA men's basketball season",
    '1914–15': "NCAA men's basketball season",
    '1915–16': "NCAA men's basketball season",
    '1916–17': "NCAA men's basketball season",
    '1917–18': "NCAA men's basketball season",
    '1918–19': "NCAA men's basketball season",
    '1919–20': "NCAA men's basketball season",
    '1920–21': "NCAA men's basketball season",
    '1921–22': "NCAA men's basketball season",
    '1922–23': "NCAA men's basketball season",
    '1923–24': "NCAA men's basketball season",
    '1924–25': "NCAA men's basketball season",
    '1925–26': "NCAA men's basketball season",
    '1926–27': "NCAA men's basketball season",
    '1927–28': "NCAA men's basketball season",
    '1928–29': "NCAA men's basketball season",
    '1929–30': "NCAA men's basketball season",
    '1930–31': "NCAA men's basketball season",
    '1931–32': "NCAA men's basketball season",
    '1932–33': "NCAA men's basketball season",
    '1933–34': "NCAA men's basketball season",
    '1934–35': "NCAA men's basketball season",
    '1935–36': "NCAA men's basketball season",
    '1936–37': "NCAA men's basketball season",
    '1937–38': "NCAA men's basketball season",
    '1938–39': "NCAA men's basketball season",
    '1939–40': "NCAA men's basketball season",
    '1940–41': "NCAA men's basketball season",
    '1941–42': "NCAA men's basketball season",
    '1942–43': "NCAA men's basketball season",
    '1943–44': "NCAA men's basketball season",
    '1944–45': "NCAA men's basketball season",
    '1945–46': "NCAA men's basketball season",
    '1946–47': "NCAA men's basketball season",
    '1947–48': "NCAA men's basketball season",
    '1948–49': "NCAA men's basketball season",
    '1949–50': "NCAA men's basketball season",
    '1950–51': "NCAA men's basketball season",
    '1951–52': "NCAA men's basketball season",
    '1952–53': "NCAA men's basketball season",
    '1953–54': "NCAA men's basketball season",
    '1954–55': "NCAA men's basketball season",
    '1955–56': "NCAA men's basketball season",
    '1956–57': "NCAA University Division men's basketball season",
    '1957–58': "NCAA University Division men's basketball season",
    '1958–59': "NCAA University Division men's basketball season",
    '1959–60': "NCAA University Division men's basketball season",
    '1960–61': "NCAA University Division men's basketball season",
    '1961–62': "NCAA University Division men's basketball season",
    '1962–63': "NCAA University Division men's basketball season",
    '1963–64': "NCAA University Division men's basketball season",
    '1964–65': "NCAA University Division men's basketball season",
    '1965–66': "NCAA University Division men's basketball season",
    '1966–67': "NCAA University Division men's basketball season",
    '1967–68': "NCAA University Division men's basketball season",
    '1968–69': "NCAA University Division men's basketball season",
    '1969–70': "NCAA University Division men's basketball season",
    '1970–71': "NCAA University Division men's basketball season",
    '1971–72': "NCAA University Division men's basketball season",
    '1972–73': "NCAA University Division men's basketball season",
    '1973–74': "NCAA Division I men's basketball season",
    '1974–75': "NCAA Division I men's basketball season",
    '1975–76': "NCAA Division I men's basketball season",
    '1976–77': "NCAA Division I men's basketball season",
    '1977–78': "NCAA Division I men's basketball season",
    '1978–79': "NCAA Division I men's basketball season",
    '1979–80': "NCAA Division I men's basketball season",
    '1980–81': "NCAA Division I men's basketball season",
    '1981–82': "NCAA Division I men's basketball season",
    '1982–83': "NCAA Division I men's basketball season",
    '1983–84': "NCAA Division I men's basketball season",
    '1984–85': "NCAA Division I men's basketball season",
    '1985–86': "NCAA Division I men's basketball season",
    '1986–87': "NCAA Division I men's basketball season",
    '1987–88': "NCAA Division I men's basketball season",
    '1988–89': "NCAA Division I men's basketball season",
    '1989–90': "NCAA Division I men's basketball season",
    '1990–91': "NCAA Division I men's basketball season",
    '1991–92': "NCAA Division I men's basketball season",
    '1992–93': "NCAA Division I men's basketball season",
    '1993–94': "NCAA Division I men's basketball season",
    '1994–95': "NCAA Division I men's basketball season",
    '1995–96': "NCAA Division I men's basketball season",
    '1996–97': "NCAA Division I men's basketball season",
    '1997–98': "NCAA Division I men's basketball season",
    '1998–99': "NCAA Division I men's basketball season",
    '1999–2000': "NCAA Division I men's basketball season",
    '2000–01': "NCAA Division I men's basketball season",
    '2001–02': "NCAA Division I men's basketball season",
    '2002–03': "NCAA Division I men's basketball season",
    '2003–04': "NCAA Division I men's basketball season",
    '2004–05': "NCAA Division I men's basketball season",
    '2005–06': "NCAA Division I men's basketball season",
    '2006–07': "NCAA Division I men's basketball season",
    '2007–08': "NCAA Division I men's basketball season",
    '2008–09': "NCAA Division I men's basketball season",
    '2009–10': "NCAA Division I men's basketball season",
    '2010–11': "NCAA Division I men's basketball season",
    '2011–12': "NCAA Division I men's basketball season",
    '2012–13': "NCAA Division I men's basketball season",
    '2013–14': "NCAA Division I men's basketball season",
    '2014–15': "NCAA Division I men's basketball season",
    '2015–16': "NCAA Division I men's basketball season",
    '2016 ncaa tournament': "2016 NCAA Division I men's basketball tournament",
    '2016–17': "NCAA Division I men's basketball season",
    '2017–18': "NCAA Division I men's basketball season",
    '2018 ncaa tournament': "2018 NCAA Division I men's basketball tournament",
    '2018–19': "NCAA Division I men's basketball season",
    '2019–20': "NCAA Division I men's basketball season",
    '2020–21': "NCAA Division I men's basketball season",
    '2021–22': "NCAA Division I men's basketball season",
    '2022–23': "NCAA Division I men's basketball season",
    '2023–24': "NCAA Division I men's basketball season",
    '2024–25': "NCAA Division I men's basketball season",
    "2025–26 acc men's basketball standings": "Atlantic Coast Conference men's basketball season",
    "2025–26 atlantic 10 men's basketball standings": "Atlantic 10 Conference men's basketball season",
    "2025–26 big 12 men's basketball standings": "Big 12 Conference men's basketball season",
    "2025–26 big ten conference men's basketball standings": "Big Ten Conference men's basketball season",
    "2025–26 horizon league men's basketball standings": "Horizon League men's basketball season",
    "2025–26 meac men's basketball standings": "Mid-Eastern Athletic Conference men's basketball season",
    "2025–26 mid-american conference men's basketball standings": "Mid-American Conference men's basketball season",
    "2025–26 missouri valley conference men's basketball standings": "Missouri Valley Conference men's basketball season",
    "2025–26 ncaa division i men's basketball rankings": "NCAA Division I men's basketball rankings",
    "2025–26 ncaa division i women's basketball season": "NCAA Division I women's basketball season",
    "2025–26 nec men's basketball standings": "Northeast Conference men's basketball season",
    '2025–26 season': "Cal State Bakersfield Roadrunners men's basketball",
    "2025–26 southeastern conference men's basketball standings": "Southeastern Conference men's basketball season",
    "2025–26 summit league men's basketball standings": "Summit League men's basketball season",
    "2025–26 sun belt conference men's basketball standings": "Sun Belt Conference men's basketball season",
    "2025–26 wac men's basketball standings": "Western Athletic Conference men's basketball season",
    "2025–26 west coast conference men's basketball standings": "West Coast Conference men's basketball season",
    'abilene christian': "Abilene Christian Wildcats men's basketball",
    'academic all-american of the year': "List of Men's Basketball Academic All-America Team Members of the Year",
    'air force': "Air Force Falcons men's basketball",
    'akron': "Akron Zips men's basketball",
    'akron zips': "Akron Zips men's basketball",
    'alabama': "Alabama Crimson Tide men's basketball",
    'alabama a&m': "Alabama A&M Bulldogs basketball",
    'alabama st': "Alabama State Hornets basketball",
    'alabama st.': "Alabama State Hornets basketball",
    'alabama state': "Alabama State Hornets basketball",
    'albany': "Albany Great Danes men's basketball",
    'alcorn st braves': "Alcorn State Braves basketball",
    'alcorn st.': "Alcorn State Braves basketball",
    'alcorn st. braves': "Alcorn State Braves basketball",
    'alcorn state braves': "Alcorn State Braves basketball",
    'american': "American Eagles men's basketball",
    'ap poll': "NCAA Division I men's basketball rankings",
    'app state': "Appalachian State Mountaineers men\'s basketball",
    'appalachian st': "Appalachian State Mountaineers men's basketball",
    'appalachian st.': "Appalachian State Mountaineers men's basketball",
    'appalachian state': "Appalachian State Mountaineers men's basketball",
    'arizona': "Arizona Wildcats men's basketball",
    'arizona st': "Arizona State Sun Devils men's basketball",
    'arizona st.': "Arizona State Sun Devils men's basketball",
    'arizona state': "Arizona State Sun Devils men's basketball",
    'arkansas': "Arkansas Razorbacks men's basketball",
    'arkansas pine bluff': "Arkansas–Pine Bluff Golden Lions men's basketball",
    'arkansas st': "Arkansas State Red Wolves men\'s basketball",
    'arkansas st red wolves': "Arkansas State Red Wolves men's basketball",
    'arkansas st.': "Arkansas State Red Wolves men\'s basketball",
    'arkansas st. red wolves': "Arkansas State Red Wolves men's basketball",
    'arkansas state': "Arkansas State Red Wolves men's basketball",
    'arkansas state red wolves': "Arkansas State Red Wolves men's basketball",
    'arkansas–pine bluff golden': "Arkansas–Pine Bluff Golden Lions men's basketball",
    'arkansas–pine bluff golden lions': "Arkansas–Pine Bluff Golden Lions men's basketball",
    'army': "Army Black Knights men's basketball",
    'army black': "Army Black Knights men's basketball",
    'auburn': "Auburn Tigers men's basketball",
    'austin peay': "Austin Peay Governors men's basketball",
    'austin peay governors': "Austin Peay Governors men's basketball",
    'ball st': "Ball State Cardinals men's basketball",
    'ball st.': "Ball State Cardinals men's basketball",
    'ball state': "Ball State Cardinals men's basketball",
    'baylor': "Baylor Bears men's basketball",
    'bellarmine': "Bellarmine Knights men's basketball",
    'belmont': "Belmont Bruins men's basketball",
    'bethune cookman': "Bethune–Cookman Wildcats men's basketball",
    'bethune–cookman': "Bethune–Cookman Wildcats men's basketball",
    'bethune–cookman wildcats': "Bethune–Cookman Wildcats men's basketball",
    'binghamton': "Binghamton Bearcats men's basketball",
    'boise st': "Boise State Broncos men's basketball",
    'boise st.': "Boise State Broncos men's basketball",
    'boise state': "Boise State Broncos men's basketball",
    'boston college': "Boston College Eagles men's basketball",
    'boston university': "Boston University Terriers men's basketball",
    'bowling green': "Bowling Green Falcons men's basketball",
    'bradley': "Bradley Braves men's basketball",
    'bradley braves': "Bradley Braves men's basketball",
    'brigham young': "BYU Cougars men\'s basketball",
    'brown': "Brown Bears men's basketball",
    'bryant': "Bryant Bulldogs men's basketball",
    'bucknell': "Bucknell Bison men's basketball",
    'buffalo': "Buffalo Bulls men's basketball",
    'butler': "Butler Bulldogs men's basketball",
    'byu': "BYU Cougars men's basketball",
    'cal baptist': "California Baptist Lancers men's basketball",
    'cal poly': "Cal Poly Mustangs men's basketball",
    'cal st bakersfield roadrunners': "Cal State Bakersfield Roadrunners men's basketball",
    'cal st fullerton': "Cal State Fullerton Titans men's basketball",
    'cal st northridge matadors': "Cal State Northridge Matadors men's basketball",
    'cal st. bakersfield roadrunners': "Cal State Bakersfield Roadrunners men's basketball",
    'cal st. fullerton': "Cal State Fullerton Titans men's basketball",
    'cal st. northridge matadors': "Cal State Northridge Matadors men's basketball",
    'cal state bakersfield': "Cal State Bakersfield Roadrunners men's basketball",
    'cal state bakersfield roadrunners': "Cal State Bakersfield Roadrunners men's basketball",
    'cal state fullerton': "Cal State Fullerton Titans men's basketball",
    'cal state northridge': "Cal State Northridge Matadors men's basketball",
    'cal state northridge matadors': "Cal State Northridge Matadors men's basketball",
    'california': "California Golden Bears men's basketball",
    'california baptist': "California Baptist Lancers men's basketball",
    'california baptist lancers': "California Baptist Lancers men's basketball",
    'california golden': "California Golden Bears men's basketball",
    'campbell': "Campbell Fighting Camels men's basketball",
    'campbell fighting camels': "Campbell Fighting Camels basketball",
    'canisius': "Canisius Golden Griffins men's basketball",
    'canisius golden griffins': "Canisius Golden Griffins men's basketball",
    'central arkansas': "Central Arkansas Bears basketball",
    'central connecticut': "Central Connecticut Blue Devils men's basketball",
    'central florida': "UCF Knights men's basketball",
    'central michigan': "Central Michigan Chippewas men's basketball",
    'central michigan chippewas': "Central Michigan Chippewas men's basketball",
    'charleston': "Charleston Cougars men's basketball",
    'charleston southern': "Charleston Southern Buccaneers men's basketball",
    'charlotte': "Charlotte 49ers men's basketball",
    'charlotte 49ers': "Charlotte 49ers men's basketball",
    'chattanooga': "Chattanooga Mocs men's basketball",
    'chattanooga mocs': "Chattanooga Mocs men's basketball",
    'chicago st': "Chicago State Cougars men's basketball",
    'chicago st.': "Chicago State Cougars men's basketball",
    'chicago state': "Chicago State Cougars men's basketball",
    'cincinnati': "Cincinnati Bearcats men's basketball",
    'clemson': "Clemson Tigers men's basketball",
    'cleveland st': "Cleveland State Vikings men's basketball",
    'cleveland st.': "Cleveland State Vikings men's basketball",
    'cleveland state': "Cleveland State Vikings men's basketball",
    'coastal carolina': "Coastal Carolina Chanticleers men's basketball",
    'colgate': "Colgate Raiders men's basketball",
    'colorado': "Colorado Buffaloes men's basketball",
    'colorado st': "Colorado State Rams men's basketball",
    'colorado st.': "Colorado State Rams men's basketball",
    'colorado state': "Colorado State Rams men's basketball",
    'columbia': "Columbia Lions men's basketball",
    'connecticut': "UConn Huskies men's basketball",
    'coppin st': "Coppin State Eagles men's basketball",
    'coppin st.': "Coppin State Eagles men's basketball",
    'coppin state': "Coppin State Eagles men's basketball",
    'cornell': "Cornell Big Red men's basketball",
    'cornell big red': "Cornell Big Red men's basketball",
    'creighton': "Creighton Bluejays men's basketball",
    'creighton bluejays': "Creighton Bluejays men's basketball",
    'dartmouth': "Dartmouth Big Green men's basketball",
    'dartmouth big green': "Dartmouth Big Green men's basketball",
    'davidson': "Davidson Wildcats men's basketball",
    'dayton': "Dayton Flyers men's basketball",
    'dayton flyers': "Dayton Flyers men's basketball",
    'delaware': "Delaware Fightin' Blue Hens men's basketball",
    "delaware fightin'": "Delaware Fightin' Blue Hens men's basketball",
    'delaware st': "Delaware State Hornets men's basketball",
    'delaware st.': "Delaware State Hornets men's basketball",
    'delaware state': "Delaware State Hornets men's basketball",
    'denver': "Denver Pioneers men's basketball",
    'denver pioneers': "Denver Pioneers men's basketball",
    'depaul': "DePaul Blue Demons men's basketball",
    'depaul blue': "DePaul Blue Demons men's basketball",
    'detroit mercy': "Detroit Mercy Titans men's basketball",
    'dixie state': "Utah Tech Trailblazers men\'s basketball",
    'drake': "Drake Bulldogs men's basketball",
    'drexel': "Drexel Dragons men's basketball",
    'duke': "Duke Blue Devils men's basketball",
    'duquesne': "Duquesne Dukes men's basketball",
    'east carolina': "East Carolina Pirates men's basketball",
    'east tennessee st': "East Tennessee State Buccaneers men's basketball",
    'east tennessee st.': "East Tennessee State Buccaneers men's basketball",
    'east tennessee state': "East Tennessee State Buccaneers men's basketball",
    'east texas a&m': "East Texas A&M Lions men's basketball",
    'eastern illinois': "Eastern Illinois Panthers men's basketball",
    'eastern kentucky': "Eastern Kentucky Colonels men's basketball",
    'eastern michigan': "Eastern Michigan Eagles men's basketball",
    'eastern washington': "Eastern Washington Eagles men's basketball",
    'elon': "Elon Phoenix men's basketball",
    'evansville': "Evansville Purple Aces men's basketball",
    'evansville purple aces': "Evansville Purple Aces men's basketball",
    'fairfield': "Fairfield Stags men's basketball",
    'fairfield stags': "Fairfield Stags men's basketball",
    'fairleigh dickinson': "Fairleigh Dickinson Knights men's basketball",
    'fau': "Florida Atlantic Owls men's basketball",
    'fiu': "FIU Panthers men's basketball",
    'florida': "Florida Gators men's basketball",
    'florida a&m': "Florida A&M Rattlers basketball",
    'florida a&m rattlers': "Florida A&M Rattlers basketball",
    'florida atlantic': "Florida Atlantic Owls men's basketball",
    'florida gulf coast': "Florida Gulf Coast Eagles men's basketball",
    'florida international': "FIU Panthers men's basketball",
    'florida st': "Florida State Seminoles men's basketball",
    'florida st.': "Florida State Seminoles men's basketball",
    'florida state': "Florida State Seminoles men's basketball",
    'fordham': "Fordham Rams men's basketball",
    'fresno st': "Fresno State Bulldogs men's basketball",
    'fresno st.': "Fresno State Bulldogs men's basketball",
    'fresno state': "Fresno State Bulldogs men's basketball",
    'furman': "Furman Paladins men's basketball",
    'furman paladins': "Furman Paladins men's basketball",
    'ga. southern': "Georgia Southern Eagles men\'s basketball",
    'gardner webb': "Gardner–Webb Runnin' Bulldogs men's basketball",
    'gardner–webb': "Gardner–Webb Runnin' Bulldogs men's basketball",
    "gardner–webb runnin'": "Gardner–Webb Runnin' Bulldogs men's basketball",
    "gardner–webb runnin' bulldogs": "Gardner–Webb Runnin' Bulldogs men's basketball",
    'george mason': "George Mason Patriots men's basketball",
    'george washington': "George Washington Revolutionaries men's basketball",
    'george washington revolutionaries': "George Washington Revolutionaries men's basketball",
    'georgetown': "Georgetown Hoyas men's basketball",
    'georgetown hoyas': "Georgetown Hoyas men's basketball",
    'georgia': "Georgia Bulldogs basketball",
    'georgia southern': "Georgia Southern Eagles men's basketball",
    'georgia st': "Georgia State Panthers men's basketball",
    'georgia st.': "Georgia State Panthers men's basketball",
    'georgia state': "Georgia State Panthers men's basketball",
    'georgia tech': "Georgia Tech Yellow Jackets men's basketball",
    'georgia tech yellow jackets': "Georgia Tech Yellow Jackets men's basketball",
    'gonzaga': "Gonzaga Bulldogs men's basketball",
    'grambling st': "Grambling State Tigers men's basketball",
    'grambling st.': "Grambling State Tigers men's basketball",
    'grambling state': "Grambling State Tigers men's basketball",
    'grand canyon': "Grand Canyon Antelopes men's basketball",
    'grand canyon antelopes': "Grand Canyon Antelopes men's basketball",
    'green bay': "Green Bay Phoenix men's basketball",
    'hampton': "Hampton Pirates men's basketball",
    'harvard': "Harvard Crimson men's basketball",
    'harvard crimson': "Harvard Crimson men's basketball",
    'hawaii': "Hawaii Rainbow Warriors basketball",
    'hawaii rainbow warriors': "Hawaii Rainbow Warriors basketball",
    'high point': "High Point Panthers men's basketball",
    'hofstra': "Hofstra Pride men's basketball",
    'hofstra pride': "Hofstra Pride men's basketball",
    'holy cross': "Holy Cross Crusaders men's basketball",
    'houston': "Houston Cougars men's basketball",
    'houston baptist': "Houston Christian Huskies men\'s basketball",
    'houston christian': "Houston Christian Huskies men's basketball",
    'howard': "Howard Bison men's basketball",
    'idaho': "Idaho Vandals men's basketball",
    'idaho st bengals': "Idaho State Bengals men's basketball",
    'idaho st.': "Idaho State Bengals men's basketball",
    'idaho st. bengals': "Idaho State Bengals men's basketball",
    'idaho state': "Idaho State Bengals men's basketball",
    'idaho state bengals': "Idaho State Bengals men's basketball",
    'idaho vandals': "Idaho Vandals men's basketball",
    'illinois': "Illinois Fighting Illini men's basketball",
    'illinois chicago': "UIC Flames men's basketball",
    'illinois st redbirds': "Illinois State Redbirds men's basketball",
    'illinois st.': "Illinois State Redbirds men's basketball",
    'illinois st. redbirds': "Illinois State Redbirds men's basketball",
    'illinois state': "Illinois State Redbirds men's basketball",
    'illinois state redbirds': "Illinois State Redbirds men's basketball",
    'incarnate word': "Incarnate Word Cardinals men's basketball",
    'indiana': "Indiana Hoosiers men's basketball",
    'indiana st sycamores': "Indiana State Sycamores men's basketball",
    'indiana st.': "Indiana State Sycamores men's basketball",
    'indiana st. sycamores': "Indiana State Sycamores men's basketball",
    'indiana state': "Indiana State Sycamores men's basketball",
    'indiana state sycamores': "Indiana State Sycamores men's basketball",
    'iona': "Iona Gaels men's basketball",
    'iona gaels': "Iona Gaels men's basketball",
    'iowa': "Iowa Hawkeyes men's basketball",
    'iowa hawkeyes': "Iowa Hawkeyes men's basketball",
    'iowa st': "Iowa State Cyclones men's basketball",
    'iowa st.': "Iowa State Cyclones men's basketball",
    'iowa state': "Iowa State Cyclones men's basketball",
    'iu indy': "IU Indy Jaguars men's basketball",
    'jackson st': "Jackson State Tigers basketball",
    'jackson st.': "Jackson State Tigers basketball",
    'jackson state': "Jackson State Tigers basketball",
    'jacksonville': "Jacksonville Dolphins men's basketball",
    'jacksonville st gamecocks': "Jacksonville State Gamecocks men's basketball",
    'jacksonville st.': "Jacksonville State Gamecocks men's basketball",
    'jacksonville st. gamecocks': "Jacksonville State Gamecocks men's basketball",
    'jacksonville state': "Jacksonville State Gamecocks men's basketball",
    'jacksonville state gamecocks': "Jacksonville State Gamecocks men's basketball",
    'james madison': "James Madison Dukes men's basketball",
    'kansas': "Kansas Jayhawks men's basketball",
    'kansas city': "Kansas City Roos men's basketball",
    'kansas st': "Kansas State Wildcats men's basketball",
    'kansas st.': "Kansas State Wildcats men's basketball",
    'kansas state': "Kansas State Wildcats men's basketball",
    'kennesaw st': "Kennesaw State Owls men's basketball",
    'kennesaw st.': "Kennesaw State Owls men's basketball",
    'kennesaw state': "Kennesaw State Owls men's basketball",
    'kent st': "Kent State Golden Flashes men's basketball",
    'kent st.': "Kent State Golden Flashes men's basketball",
    'kent state': "Kent State Golden Flashes men's basketball",
    'kentucky': "Kentucky Wildcats men's basketball",
    'la salle': "La Salle Explorers men's basketball",
    'lafayette': "Lafayette Leopards men's basketball",
    'lafayette leopards': "Lafayette Leopards men's basketball",
    'lamar': "Lamar Cardinals basketball",
    'le moyne': "Le Moyne Dolphins men's basketball",
    'lehigh': "Lehigh Mountain Hawks men's basketball",
    'lehigh mountain': "Lehigh Mountain Hawks men's basketball",
    'liberty': "Liberty Flames basketball",
    'lindenwood': "Lindenwood Lions men's basketball",
    'lipscomb': "Lipscomb Bisons men's basketball",
    'lipscomb bisons': "Lipscomb Bisons men's basketball",
    'little rock': "Little Rock Trojans men's basketball",
    'liu': "LIU Sharks men's basketball",
    'liu sharks': "LIU Sharks men's basketball",
    'lmu': "Loyola Marymount Lions men\'s basketball",
    'long beach st beach': "Long Beach State Beach men's basketball",
    'long beach st.': "Long Beach State Beach men's basketball",
    'long beach st. beach': "Long Beach State Beach men's basketball",
    'long beach state': "Long Beach State Beach men's basketball",
    'long beach state beach': "Long Beach State Beach men's basketball",
    'longwood': "Longwood Lancers men's basketball",
    'longwood lancers': "Longwood Lancers men's basketball",
    'louisiana': "Louisiana Ragin' Cajuns men's basketball",
    'louisiana lafayette': "Louisiana Ragin\' Cajuns men\'s basketball",
    'louisiana monroe': "Louisiana–Monroe Warhawks men\'s basketball",
    "louisiana ragin' cajuns": "Louisiana Ragin' Cajuns men's basketball",
    'louisiana state': "LSU Tigers men's basketball",
    'louisiana tech': "Louisiana Tech Bulldogs men's basketball",
    'louisiana–monroe': "Louisiana–Monroe Warhawks men's basketball",
    'louisiana–monroe warhawks': "Louisiana–Monroe Warhawks men's basketball",
    'louisville': "Louisville Cardinals men's basketball",
    'loyola': "Loyola Greyhounds men's basketball",
    'loyola chicago': "Loyola Ramblers men's basketball",
    'loyola greyhounds': "Loyola Greyhounds men's basketball",
    'loyola marymount': "Loyola Marymount Lions men's basketball",
    'loyola marymount lions': "Loyola Marymount Lions men's basketball",
    'loyola md': "Loyola Greyhounds men's basketball",
    'loyola ramblers': "Loyola Ramblers men's basketball",
    'lsu': "LSU Tigers men's basketball",
    'maine': "Maine Black Bears men's basketball",
    'maine black': "Maine Black Bears men's basketball",
    'manhattan': "Manhattan Jaspers men's basketball",
    'manhattan jaspers': "Manhattan Jaspers basketball",
    'marist': "Marist Red Foxes men's basketball",
    'marist red foxes': "Marist Red Foxes men's basketball",
    'marquette': "Marquette Golden Eagles men's basketball",
    'marquette golden': "Marquette Golden Eagles men's basketball",
    'marshall': "Marshall Thundering Herd men's basketball",
    'marshall thundering herd': "Marshall Thundering Herd men's basketball",
    'maryland': "Maryland Terrapins men's basketball",
    'maryland baltimore county': "UMBC Retrievers men's basketball",
    'maryland eastern shore': "Maryland Eastern Shore Hawks men's basketball",
    'massachusetts': "UMass Minutemen basketball",
    'mcneese': "McNeese Cowboys basketball",
    'mcneese cowboys': "McNeese Cowboys basketball",
    'mcneese st.': "McNeese Cowboys basketball",
    'memphis': "Memphis Tigers men's basketball",
    "men's basketball team": "Loyola Ramblers men's basketball",
    'mercer': "Mercer Bears men's basketball",
    'mercyhurst': "Mercyhurst Lakers men's basketball",
    'merrimack': "Merrimack Warriors men's basketball",
    'merrimack warriors': "Merrimack Warriors men's basketball",
    'miami': "Miami Hurricanes men's basketball",
    'miami (fl)': "Miami Hurricanes men's basketball",
    'miami (oh)': "Miami RedHawks men's basketball",
    'miami fl': "Miami Hurricanes men\'s basketball",
    'miami oh': "Miami RedHawks men's basketball",
    'miami redhawks': "Miami RedHawks men's basketball",
    'michigan': "Michigan Wolverines men's basketball",
    'michigan st': "Michigan State Spartans men's basketball",
    'michigan st.': "Michigan State Spartans men's basketball",
    'michigan state': "Michigan State Spartans men's basketball",
    'middle tennessee': "Middle Tennessee Blue Raiders men's basketball",
    'middle tennessee blue': "Middle Tennessee Blue Raiders men's basketball",
    'milwaukee': "Milwaukee Panthers men's basketball",
    'minnesota': "Minnesota Golden Gophers men's basketball",
    'minnesota golden': "Minnesota Golden Gophers men's basketball",
    'mississippi': "Ole Miss Rebels men's basketball",
    'mississippi st': "Mississippi State Bulldogs basketball",
    'mississippi st.': "Mississippi State Bulldogs basketball",
    'mississippi state': "Mississippi State Bulldogs men's basketball",
    'mississippi valley st delta devils': "Mississippi Valley State Delta Devils basketball",
    'mississippi valley st.': "Mississippi Valley State Delta Devils basketball",
    'mississippi valley st. delta devils': "Mississippi Valley State Delta Devils basketball",
    'mississippi valley state delta devils': "Mississippi Valley State Delta Devils basketball",
    'missouri': "Missouri Tigers men's basketball",
    'missouri kansas city': "Kansas City Roos men's basketball",
    'missouri st': "Missouri State Bears basketball",
    'missouri st.': "Missouri State Bears basketball",
    'missouri state': "Missouri State Bears basketball",
    'monmouth': "Monmouth Hawks men's basketball",
    'montana': "Montana Grizzlies basketball",
    'montana st': "Montana State Bobcats men's basketball",
    'montana st.': "Montana State Bobcats men's basketball",
    'montana state': "Montana State Bobcats men's basketball",
    'morehead st': "Morehead State Eagles men's basketball",
    'morehead st.': "Morehead State Eagles men's basketball",
    'morehead state': "Morehead State Eagles men's basketball",
    'morgan st': "Morgan State Bears men's basketball",
    'morgan st.': "Morgan State Bears men's basketball",
    'morgan state': "Morgan State Bears men's basketball",
    "mount st mary's": "Mount St. Mary's Mountaineers men's basketball",
    "mount st. mary's": "Mount St. Mary's Mountaineers men's basketball",
    "mount state mary's": "Mount St. Mary's Mountaineers men's basketball",
    'msu': "Michigan State Spartans men\'s basketball",
    'murray st racers': "Murray State Racers men's basketball",
    'murray st.': "Murray State Racers men's basketball",
    'murray st. racers': "Murray State Racers men's basketball",
    'murray state': "Murray State Racers men's basketball",
    'murray state racers': "Murray State Racers men's basketball",
    'n.c. state': "NC State Wolfpack men's basketball",
    'navy': "Navy Midshipmen men's basketball",
    'navy midshipmen': "Navy Midshipmen men's basketball",
    'nc st': "NC State Wolfpack men's basketball",
    'nc st.': "NC State Wolfpack men's basketball",
    'nc state': "NC State Wolfpack men's basketball",
    'nc state wolfpack': "NC State Wolfpack men's basketball",
    'ncaa tournament era': "NCAA Division I men's basketball tournament",
    'ncaa tournament': "NCAA Division I men's basketball tournament",
    'nebraska': "Nebraska Cornhuskers men's basketball",
    'nebraska cornhuskers': "Nebraska Cornhuskers men's basketball",
    'nebraska omaha': "Omaha Mavericks men\'s basketball",
    'nevada': "Nevada Wolf Pack men's basketball",
    'nevada wolf pack': "Nevada Wolf Pack men's basketball",
    'new hampshire': "New Hampshire Wildcats men's basketball",
    'new haven': "New Haven Chargers men's basketball",
    'new haven chargers': "New Haven Chargers men's basketball",
    'new mexico': "New Mexico Lobos men's basketball",
    'new mexico st': "New Mexico State Aggies men's basketball",
    'new mexico st.': "New Mexico State Aggies men's basketball",
    'new mexico state': "New Mexico State Aggies men's basketball",
    'new orleans': "New Orleans Privateers men's basketball",
    'new orleans privateers': "New Orleans Privateers men's basketball",
    'niagara': "Niagara Purple Eagles men's basketball",
    'niagara purple': "Niagara Purple Eagles men's basketball",
    'nicholls': "Nicholls Colonels men's basketball",
    'nicholls colonels': "Nicholls Colonels men's basketball",
    'nicholls st.': "Nicholls Colonels men's basketball",
    'njit': "NJIT Highlanders men's basketball",
    'njit highlanders': "NJIT Highlanders men's basketball",
    'norfolk st': "Norfolk State Spartans men's basketball",
    'norfolk st.': "Norfolk State Spartans men's basketball",
    'norfolk state': "Norfolk State Spartans men's basketball",
    'north alabama': "North Alabama Lions men's basketball",
    'north carolina': "North Carolina Tar Heels men's basketball",
    'north carolina a&t': "North Carolina A&T Aggies men's basketball",
    'north carolina central': "North Carolina Central Eagles men's basketball",
    'north dakota': "North Dakota Fighting Hawks men's basketball",
    'north dakota fighting': "North Dakota Fighting Hawks men's basketball",
    'north dakota st': "North Dakota State Bison men's basketball",
    'north dakota st.': "North Dakota State Bison men's basketball",
    'north dakota state': "North Dakota State Bison men's basketball",
    'north florida': "North Florida Ospreys men's basketball",
    'north florida ospreys': "North Florida Ospreys men's basketball",
    'north texas': "North Texas Mean Green men's basketball",
    'north texas mean green': "North Texas Mean Green men's basketball",
    'northeastern': "Northeastern Huskies men's basketball",
    'northern arizona': "Northern Arizona Lumberjacks men's basketball",
    'northern arizona lumberjacks': "Northern Arizona Lumberjacks men's basketball",
    'northern colorado': "Northern Colorado Bears men's basketball",
    'northern illinois': "Northern Illinois Huskies men's basketball",
    'northern iowa': "Northern Iowa Panthers men's basketball",
    'northern kentucky': "Northern Kentucky Norse men's basketball",
    'northern kentucky norse': "Northern Kentucky Norse men's basketball",
    'northwestern': "Northwestern Wildcats men's basketball",
    'northwestern st': "Northwestern State Demons basketball",
    'northwestern st.': "Northwestern State Demons basketball",
    'northwestern state': "Northwestern State Demons basketball",
    'notre dame': "Notre Dame Fighting Irish men's basketball",
    'notre dame fighting irish': "Notre Dame Fighting Irish men's basketball",
    'oakland': "Oakland Golden Grizzlies men's basketball",
    'oakland golden': "Oakland Golden Grizzlies men's basketball",
    'ohio': "Ohio Bobcats men's basketball",
    'ohio st buckeyes': "Ohio State Buckeyes men's basketball",
    'ohio st.': "Ohio State Buckeyes men's basketball",
    'ohio st. buckeyes': "Ohio State Buckeyes men's basketball",
    'ohio state': "Ohio State Buckeyes men's basketball",
    'ohio state buckeyes': "Ohio State Buckeyes men's basketball",
    'oklahoma': "Oklahoma Sooners men's basketball",
    'oklahoma sooners': "Oklahoma Sooners men's basketball",
    'oklahoma st': "Oklahoma State Cowboys basketball",
    'oklahoma st.': "Oklahoma State Cowboys basketball",
    'oklahoma state': "Oklahoma State Cowboys basketball",
    'old dominion': "Old Dominion Monarchs men's basketball",
    'ole miss': "Ole Miss Rebels men's basketball",
    'omaha': "Omaha Mavericks men's basketball",
    'oral roberts': "Oral Roberts Golden Eagles men's basketball",
    'oral roberts golden': "Oral Roberts Golden Eagles men's basketball",
    'oregon': "Oregon Ducks men's basketball",
    'oregon ducks': "Oregon Ducks men's basketball",
    'oregon st': "Oregon State Beavers men's basketball",
    'oregon st.': "Oregon State Beavers men's basketball",
    'oregon state': "Oregon State Beavers men's basketball",
    'pacific': "Pacific Tigers men's basketball",
    'penn': "Penn Quakers men's basketball",
    'penn quakers': "Penn Quakers men's basketball",
    'penn st nittany': "Penn State Nittany Lions basketball",
    'penn st.': "Penn State Nittany Lions basketball",
    'penn st. nittany': "Penn State Nittany Lions basketball",
    'penn state': "Penn State Nittany Lions basketball",
    'penn state nittany': "Penn State Nittany Lions basketball",
    'penn state nittany lions': "Penn State Nittany Lions basketball",
    'pepperdine': "Pepperdine Waves men's basketball",
    'pepperdine waves': "Pepperdine Waves men's basketball",
    'pittsburgh': "Pittsburgh Panthers men's basketball",
    'portland': "Portland Pilots men's basketball",
    'portland pilots': "Portland Pilots men's basketball",
    'portland st': "Portland State Vikings men's basketball",
    'portland st.': "Portland State Vikings men's basketball",
    'portland state': "Portland State Vikings men's basketball",
    'prairie view a&m': "Prairie View A&M Panthers basketball",
    'presbyterian': "Presbyterian Blue Hose men's basketball",
    'presbyterian blue hose': "Presbyterian Blue Hose men's basketball",
    'preseason ap no. 1': "NCAA Division I men's basketball rankings",
    'princeton': "Princeton Tigers men's basketball",
    'providence': "Providence Friars men's basketball",
    'providence friars': "Providence Friars men's basketball",
    'purdue': "Purdue Boilermakers men's basketball",
    'purdue boilermakers': "Purdue Boilermakers men's basketball",
    'purdue fort wayne': "Purdue Fort Wayne Mastodons men's basketball",
    'queens': "Queens Royals men's basketball",
    'queens royals': "Queens Royals men's basketball",
    'quinnipiac': "Quinnipiac Bobcats men's basketball",
    'radford': "Radford Highlanders men's basketball",
    'radford highlanders': "Radford Highlanders men's basketball",
    "ramblers' run": "Loyola Ramblers men's basketball",
    'rhode island': "Rhode Island Rams men's basketball",
    'rice': "Rice Owls men's basketball",
    'richmond': "Richmond Spiders men's basketball",
    'rider': "Rider Broncs men's basketball",
    'rider broncs': "Rider Broncs men's basketball",
    'robert morris': "Robert Morris Colonials men's basketball",
    'robert morris colonials': "Robert Morris Colonials men's basketball",
    'rutgers': "Rutgers Scarlet Knights men's basketball",
    'rutgers scarlet': "Rutgers Scarlet Knights men's basketball",
    's': "St. John\'s Red Storm men\'s basketball",
    's gaels': "Saint Mary\'s Gaels men\'s basketball",
    'sacramento st': "Sacramento State Hornets men's basketball",
    'sacramento st.': "Sacramento State Hornets men's basketball",
    'sacramento state': "Sacramento State Hornets men's basketball",
    'sacred heart': "Sacred Heart Pioneers men's basketball",
    'sacred heart pioneers': "Sacred Heart Pioneers men's basketball",
    'saint francis': "Saint Francis Red Flash men's basketball",
    'saint francis red flash': "Saint Francis Red Flash men's basketball",
    "saint joseph's": "Saint Joseph's Hawks men's basketball",
    'saint louis': "Saint Louis Billikens men's basketball",
    "saint mary's": "Saint Mary's Gaels men's basketball",
    "saint mary's gaels": "Saint Mary's Gaels men's basketball",
    "saint peter's": "Saint Peter's Peacocks men's basketball",
    'sam houston': "Sam Houston Bearkats men's basketball",
    'sam houston bearkats': "Sam Houston Bearkats men's basketball",
    'sam houston st.': "Sam Houston Bearkats men's basketball",
    'samford': "Samford Bulldogs men's basketball",
    'san diego': "San Diego Toreros men's basketball",
    'san diego st aztecs': "San Diego State Aztecs men's basketball",
    'san diego st.': "San Diego State Aztecs men's basketball",
    'san diego st. aztecs': "San Diego State Aztecs men's basketball",
    'san diego state': "San Diego State Aztecs men's basketball",
    'san diego state aztecs': "San Diego State Aztecs men's basketball",
    'san diego toreros': "San Diego Toreros men's basketball",
    'san francisco': "San Francisco Dons men's basketball",
    'san jose st': "San Jose State Spartans men's basketball",
    'san jose st.': "San Jose State Spartans men's basketball",
    'san jose state': "San Jose State Spartans men's basketball",
    'santa clara': "Santa Clara Broncos men's basketball",
    'seattle': "Seattle Redhawks men's basketball",
    'seattle u': "Seattle Redhawks men\'s basketball",
    'seton hall': "Seton Hall Pirates men's basketball",
    "seton hall's": "Seton Hall Pirates men's basketball",
    'siena': "Siena Saints men's basketball",
    'siena saints': "Siena Saints men's basketball",
    'siu edwardsville': "SIU Edwardsville Cougars men's basketball",
    'smu': "SMU Mustangs men's basketball",
    'south alabama': "South Alabama Jaguars men's basketball",
    'south carolina': "South Carolina Gamecocks men's basketball",
    'south carolina gamecocks': "South Carolina Gamecocks men's basketball",
    'south carolina st': "South Carolina State Bulldogs basketball",
    'south carolina st.': "South Carolina State Bulldogs basketball",
    'south carolina state': "South Carolina State Bulldogs basketball",
    'south dakota': "South Dakota Coyotes men's basketball",
    'south dakota coyotes': "South Dakota Coyotes men's basketball",
    'south dakota st': "South Dakota State Jackrabbits men\'s basketball",
    'south dakota st jackrabbits': "South Dakota State Jackrabbits men's basketball",
    'south dakota st.': "South Dakota State Jackrabbits men\'s basketball",
    'south dakota st. jackrabbits': "South Dakota State Jackrabbits men's basketball",
    'south dakota state': "South Dakota State Jackrabbits men's basketball",
    'south dakota state jackrabbits': "South Dakota State Jackrabbits men's basketball",
    'south florida': "South Florida Bulls men's basketball",
    'southeast missouri st': "Southeast Missouri State Redhawks men's basketball",
    'southeast missouri st.': "Southeast Missouri State Redhawks men's basketball",
    'southeast missouri state': "Southeast Missouri State Redhawks men's basketball",
    'southeastern louisiana': "Southeastern Louisiana Lions basketball",
    'southern': "Southern Jaguars basketball",
    'southern california': "USC Trojans men's basketball",
    'southern illinois': "Southern Illinois Salukis men's basketball",
    'southern indiana': "Southern Indiana Screaming Eagles men's basketball",
    'southern indiana screaming': "Southern Indiana Screaming Eagles men's basketball",
    'southern methodist': "SMU Mustangs men's basketball",
    'southern miss': "Southern Miss Golden Eagles men\'s basketball",
    'southern miss golden': "Southern Miss Golden Eagles basketball",
    'southern miss.': "Southern Miss Golden Eagles men\'s basketball",
    'southern mississippi': "Southern Miss Golden Eagles men\'s basketball",
    'southern utah': "Southern Utah Thunderbirds men's basketball",
    'southern utah thunderbirds': "Southern Utah Thunderbirds men's basketball",
    'st. bonaventure': "St. Bonaventure Bonnies men's basketball",
    'st. bonaventure bonnies': "St. Bonaventure Bonnies men's basketball",
    "st. john's": "St. John's Red Storm men's basketball",
    'st. thomas': "St. Thomas (Minnesota) Tommies men's basketball",
    'stanford': "Stanford Cardinal men's basketball",
    'stanford cardinal': "Stanford Cardinal men's basketball",
    'stephen f. austin': "Stephen F. Austin Lumberjacks basketball",
    'stephen f. austin lumberjacks': "Stephen F. Austin Lumberjacks basketball",
    'stetson': "Stetson Hatters men's basketball",
    'stetson hatters': "Stetson Hatters men's basketball",
    'stonehill': "Stonehill Skyhawks men's basketball",
    'stonehill skyhawks': "Stonehill Skyhawks men's basketball",
    'stony brook': "Stony Brook Seawolves men's basketball",
    'stony brook seawolves': "Stony Brook Seawolves men's basketball",
    'syracuse': "Syracuse Orange men's basketball",
    'tarleton st': "Tarleton State Texans men\'s basketball",
    'tarleton st texans': "Tarleton State Texans men's basketball",
    'tarleton st.': "Tarleton State Texans men\'s basketball",
    'tarleton st. texans': "Tarleton State Texans men's basketball",
    'tarleton state': "Tarleton State Texans men's basketball",
    'tarleton state texans': "Tarleton State Texans men's basketball",
    'tcu': "TCU Horned Frogs men's basketball",
    'tcu horned frogs': "TCU Horned Frogs men's basketball",
    'temple': "Temple Owls men's basketball",
    'tennessee': "Tennessee Volunteers basketball",
    'tennessee martin': "UT Martin Skyhawks men's basketball",
    'tennessee st': "Tennessee State Tigers basketball",
    'tennessee st.': "Tennessee State Tigers basketball",
    'tennessee state': "Tennessee State Tigers basketball",
    'tennessee tech': "Tennessee Tech Golden Eagles men's basketball",
    'tennessee tech golden': "Tennessee Tech Golden Eagles men's basketball",
    'texas': "Texas Longhorns men's basketball",
    'texas a&m': "Texas A&M Aggies men's basketball",
    'texas a&m corpus chris': "Texas A&M–Corpus Christi Islanders men's basketball",
    'texas a&m–corpus christi': "Texas A&M–Corpus Christi Islanders men's basketball",
    'texas a&m–corpus christi islanders': "Texas A&M–Corpus Christi Islanders men's basketball",
    'texas arlington': "UT Arlington Mavericks men\'s basketball",
    'texas southern': "Texas Southern Tigers basketball",
    'texas st': "Texas State Bobcats men's basketball",
    'texas st.': "Texas State Bobcats men's basketball",
    'texas state': "Texas State Bobcats men's basketball",
    'texas tech': "Texas Tech Red Raiders basketball",
    'texas tech red': "Texas Tech Red Raiders basketball",
    'texas-san antonio': "UTSA Roadrunners men\'s basketball",
    'the citadel': "The Citadel Bulldogs basketball",
    'toledo': "Toledo Rockets men's basketball",
    'toledo rockets': "Toledo Rockets men's basketball",
    'towson': "Towson Tigers men's basketball",
    'troy': "Troy Trojans men's basketball",
    'tulane': "Tulane Green Wave men's basketball",
    'tulane green wave': "Tulane Green Wave men's basketball",
    'tulsa': "Tulsa Golden Hurricane men's basketball",
    'tulsa golden hurricane': "Tulsa Golden Hurricane men's basketball",
    'uab': "UAB Blazers men's basketball",
    'uab blazers': "UAB Blazers men's basketball",
    'uc davis': "UC Davis Aggies men's basketball",
    'uc irvine': "UC Irvine Anteaters men's basketball",
    'uc riverside': "UC Riverside Highlanders men's basketball",
    'uc riverside highlanders': "UC Riverside Highlanders men's basketball",
    'uc san diego': "UC San Diego Tritons men's basketball",
    'uc san diego tritons': "UC San Diego Tritons men's basketball",
    'uc santa barbara': "UC Santa Barbara Gauchos men's basketball",
    'uc santa barbara gauchos': "UC Santa Barbara Gauchos men's basketball",
    'ucf': "UCF Knights men's basketball",
    'ucla': "UCLA Bruins men's basketball",
    'uconn': "UConn Huskies men's basketball",
    'uconn huskies': "UConn Huskies men's basketball",
    'uic': "UIC Flames men's basketball",
    'ulm': "Louisiana–Monroe Warhawks men\'s basketball",
    'umass': "UMass Minutemen basketball",
    'umass lowell': "UMass Lowell River Hawks men's basketball",
    'umass lowell river': "UMass Lowell River Hawks men's basketball",
    'umbc': "UMBC Retrievers men's basketball",
    'umkc': "Kansas City Roos men's basketball",
    'unc': "North Carolina Tar Heels men\'s basketball",
    'unc asheville': "UNC Asheville Bulldogs men's basketball",
    'unc greensboro': "UNC Greensboro Spartans men's basketball",
    'unc wilmington': "UNC Wilmington Seahawks men's basketball",
    'unc wilmington seahawks': "UNC Wilmington Seahawks men's basketball",
    'university of texas at san antonio': "UTSA Roadrunners men\'s basketball",
    'unlv': "UNLV Runnin' Rebels basketball",
    "unlv runnin'": "UNLV Runnin' Rebels basketball",
    "unlv runnin' rebels": "UNLV Runnin' Rebels basketball",
    'usc': "USC Trojans men's basketball",
    'usc upstate': "USC Upstate Spartans men's basketball",
    'ut arlington': "UT Arlington Mavericks men's basketball",
    'ut martin': "UT Martin Skyhawks men's basketball",
    'ut martin skyhawks': "UT Martin Skyhawks men's basketball",
    'ut rio grande valley': "UT Rio Grande Valley Vaqueros men's basketball",
    'ut rio grande valley vaqueros': "UT Rio Grande Valley Vaqueros men's basketball",
    'utah': "Utah Utes men's basketball",
    'utah st': "Utah State Aggies men's basketball",
    'utah st.': "Utah State Aggies men's basketball",
    'utah state': "Utah State Aggies men's basketball",
    'utah tech': "Utah Tech Trailblazers men's basketball",
    'utah tech trailblazers': "Utah Tech Trailblazers men's basketball",
    'utah valley': "Utah Valley Wolverines men's basketball",
    'utep': "UTEP Miners men's basketball",
    'utep miners': "UTEP Miners basketball",
    'utsa': "UTSA Roadrunners men's basketball",
    'utsa roadrunners': "UTSA Roadrunners men's basketball",
    'valparaiso': "Valparaiso Beacons men's basketball",
    'valparaiso beacons': "Valparaiso Beacons men's basketball",
    'vanderbilt': "Vanderbilt Commodores men's basketball",
    'vcu': "VCU Rams men's basketball",
    'vermont': "Vermont Catamounts men's basketball",
    'villanova': "Villanova Wildcats men's basketball",
    'villanova wildcats': "Villanova Wildcats men's basketball",
    'virginia': "Virginia Cavaliers men's basketball",
    'virginia commonwealth': "VCU Rams men's basketball",
    'virginia tech': "Virginia Tech Hokies men's basketball",
    'vmi': "VMI Keydets basketball",
    'vmi keydets': "VMI Keydets basketball",
    'wagner': "Wagner Seahawks men's basketball",
    'wagner seahawks': "Wagner Seahawks men's basketball",
    'wake forest': "Wake Forest Demon Deacons men's basketball",
    'washington': "Washington Huskies men's basketball",
    'washington st': "Washington State Cougars men's basketball",
    'washington st.': "Washington State Cougars men's basketball",
    'washington state': "Washington State Cougars men's basketball",
    'weber st': "Weber State Wildcats men's basketball",
    'weber st.': "Weber State Wildcats men's basketball",
    'weber state': "Weber State Wildcats men's basketball",
    'west georgia': "West Georgia Wolves men's basketball",
    'west georgia wolves': "West Georgia Wolves men's basketball",
    'west virginia': "West Virginia Mountaineers men's basketball",
    'western carolina': "Western Carolina Catamounts men's basketball",
    'western illinois': "Western Illinois Leathernecks men's basketball",
    'western illinois leathernecks': "Western Illinois Leathernecks men's basketball",
    'western kentucky': "Western Kentucky Hilltoppers basketball",
    'western kentucky hilltoppers': "Western Kentucky Hilltoppers basketball",
    'western michigan': "Western Michigan Broncos men's basketball",
    'wichita st': "Wichita State Shockers men's basketball",
    'wichita st.': "Wichita State Shockers men's basketball",
    'wichita state': "Wichita State Shockers men's basketball",
    'william & mary': "William & Mary Tribe men's basketball",
    'william & mary tribe': "William & Mary Tribe men's basketball",
    'winthrop': "Winthrop Eagles men's basketball",
    'wisconsin': "Wisconsin Badgers men's basketball",
    'wisconsin badgers': "Wisconsin Badgers men's basketball",
    'wofford': "Wofford Terriers men's basketball",
    'wright st': "Wright State Raiders men's basketball",
    'wright st.': "Wright State Raiders men's basketball",
    'wright state': "Wright State Raiders men's basketball",
    'wyoming': "Wyoming Cowboys basketball",
    'xavier': "Xavier Musketeers men's basketball",
    'yale': "Yale Bulldogs men's basketball",
    'youngstown st penguins': "Youngstown State Penguins men's basketball",
    'youngstown st.': "Youngstown State Penguins men's basketball",
    'youngstown st. penguins': "Youngstown State Penguins men's basketball",
    'youngstown state': "Youngstown State Penguins men's basketball",
    'youngstown state penguins': "Youngstown State Penguins men's basketball",
    # Additional mappings for missing teams
    'north carolina state': "NC State Wolfpack men's basketball",
    'nc state': "NC State Wolfpack men's basketball",
    'nc state wolfpack': "NC State Wolfpack men's basketball",
    'university at albany': "Albany Great Danes men's basketball",
    'albany': "Albany Great Danes men's basketball",
    'albany great danes': "Albany Great Danes men's basketball",
    'gardner-webb': "Gardner–Webb Runnin' Bulldogs men's basketball",
    'gardner webb': "Gardner–Webb Runnin' Bulldogs men's basketball",
    "hawai'i": "Hawaii Rainbow Warriors basketball",
    'hawaii': "Hawaii Rainbow Warriors basketball",
    'maryland-eastern shore': "Maryland-Eastern Shore Hawks men's basketball",
    'umes': "Maryland-Eastern Shore Hawks men's basketball",
    'central connecticut state': "Central Connecticut Blue Devils men's basketball",
    'central connecticut': "Central Connecticut Blue Devils men's basketball",
    'fdu': "FDU Knights men's basketball",
    'fairleigh dickinson': "FDU Knights men's basketball",
    'st. francis(pa)': "Saint Francis Red Flash men's basketball",
    'st francis(pa)': "Saint Francis Red Flash men's basketball",
    'saint francis': "Saint Francis Red Flash men's basketball",
    'tennessee-martin': "UT Martin Skyhawks men's basketball",
    'ut martin': "UT Martin Skyhawks men's basketball",
    'loyola maryland': "Loyola Greyhounds men's basketball",
    'loyola (md)': "Loyola Greyhounds men's basketball",
    'texas a&m-corpus christi': "Texas A&M–Corpus Christi Islanders basketball",
    'tamucc': "Texas A&M–Corpus Christi Islanders basketball",
    'arkansas-pine bluff': "Arkansas–Pine Bluff Golden Lions men's basketball",
    'uapb': "Arkansas–Pine Bluff Golden Lions men's basketball",
    'bethune-cookman': "Bethune–Cookman Wildcats men's basketball",
    'bethune cookman': "Bethune–Cookman Wildcats men's basketball",
    'louisiana-monroe': "Louisiana–Monroe Warhawks basketball",
    'ulm': "Louisiana–Monroe Warhawks basketball",
}


def get_wikipedia_page_title_safe(team_name):
    """
    Get Wikipedia page title for a team name with fallback logic.
    
    Args:
        team_name: Team name (e.g., "UCLA", "Michigan State", "Oregon")
    
    Returns:
        Wikipedia page title, or None if not found
    """
    # Normalize team name
    team_key = team_name.lower().strip()
    
    # Remove common suffixes/abbreviations for matching
    normalized = team_key
    # Remove trailing periods and common abbreviations
    normalized = normalized.rstrip('.')
    # Normalize "st." to "state" for matching
    normalized = normalized.replace(' st.', ' state').replace(' st ', ' state ')
    
    # Try direct mapping with original key
    if team_key in TEAM_WIKIPEDIA_MAPPING:
        return TEAM_WIKIPEDIA_MAPPING[team_key]
    
    # Try normalized key
    if normalized in TEAM_WIKIPEDIA_MAPPING:
        return TEAM_WIKIPEDIA_MAPPING[normalized]
    
    # Try Big Ten mapping
    big_ten_mapping = load_big_ten_mapping()
    if team_key in big_ten_mapping:
        return big_ten_mapping[team_key]
    if normalized in big_ten_mapping:
        return big_ten_mapping[normalized]
    
    # Return None if no mapping found
    # Explicit mappings are required for accuracy
    return None

